package vip.wuzhilian.bean;

import java.math.BigDecimal;

public class Costume {
    @Override
    public String toString() {
        return "Costume{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", gender='" + gender + '\'' +
                ", location='" + location + '\'' +
                ", price=" + price +
                ", isSelling='" + isSelling + '\'' +
                ", amount=" + amount +
                ", stock=" + stock +
                ", rentTimes=" + rentTimes +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costumes.id
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costumes.name
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costumes.gender
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costumes.location
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costumes.price
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costumes.is_selling
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    private String isSelling;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costumes.amount
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costumes.stock
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column costumes.rent_times
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    private Integer rentTimes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column costumes.id
     *
     * @return the value of costumes.id
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column costumes.id
     *
     * @param id the value for costumes.id
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column costumes.name
     *
     * @return the value of costumes.name
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column costumes.name
     *
     * @param name the value for costumes.name
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column costumes.gender
     *
     * @return the value of costumes.gender
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column costumes.gender
     *
     * @param gender the value for costumes.gender
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column costumes.location
     *
     * @return the value of costumes.location
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column costumes.location
     *
     * @param location the value for costumes.location
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column costumes.price
     *
     * @return the value of costumes.price
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column costumes.price
     *
     * @param price the value for costumes.price
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column costumes.is_selling
     *
     * @return the value of costumes.is_selling
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    public String getIsSelling() {
        return isSelling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column costumes.is_selling
     *
     * @param isSelling the value for costumes.is_selling
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    public void setIsSelling(String isSelling) {
        this.isSelling = isSelling == null ? null : isSelling.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column costumes.amount
     *
     * @return the value of costumes.amount
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column costumes.amount
     *
     * @param amount the value for costumes.amount
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column costumes.stock
     *
     * @return the value of costumes.stock
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column costumes.stock
     *
     * @param stock the value for costumes.stock
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column costumes.rent_times
     *
     * @return the value of costumes.rent_times
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    public Integer getRentTimes() {
        return rentTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column costumes.rent_times
     *
     * @param rentTimes the value for costumes.rent_times
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    public void setRentTimes(Integer rentTimes) {
        this.rentTimes = rentTimes;
    }
}