package vip.wuzhilian.bean;

public class Customer {
    @Override
    public String toString() {
        return "Customer{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", tel='" + tel + '\'' +
                ", companyId=" + companyId +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.id
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.name
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.TEL
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customers.company_id
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    private Integer companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.id
     *
     * @return the value of customers.id
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.id
     *
     * @param id the value for customers.id
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.name
     *
     * @return the value of customers.name
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.name
     *
     * @param name the value for customers.name
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.TEL
     *
     * @return the value of customers.TEL
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.TEL
     *
     * @param tel the value for customers.TEL
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customers.company_id
     *
     * @return the value of customers.company_id
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customers.company_id
     *
     * @param companyId the value for customers.company_id
     *
     * @mbg.generated Mon Jul 29 22:34:28 CST 2019
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }
}